services:
  - type: web
    name: bullbearmagnet
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
